server:
  port: 4006

spring:
  application:
    name: hystrix-turbine
eureka:
  client:
    service-url:
      defaultZone: http://peer1:2000/eureka/
  instance:
    prefer-ip-address: true
turbine:
  app-config: eureka-ribbon-hystrix-consumer
  cluster-name-expression: "'default'"
