server:
  port: 5000

spring:
  application:
    name: gateway-zuul-eureka



eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:2000/eureka/



management:
  security:
    enabled: false

zuul:
  routes:
    #eureka-client: /client/**  #自定义指定微服务地址 localhost:5000/client/** -->  /eureka-client/**
  #ignored-services: eureka-client  #忽略微服务 多个，隔开  使用'*'忽略所有微服务
  #ignored-patterns: /api/** #忽略路径
    client:
      path: /client/**
      serviceId: eureka-client


