server:
  port: 3000

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shimh-develop/SpringCloud-Learn
          clone-on-start: true


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://peer1:2000/eureka/


