server:
  port: 5001

spring:
  application:
    name: nacos-discovery-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        register-enabled: false # 不向注册中心注册自己 只做为消费者

# 开启 Endpoint 端点
management:
  endpoints:
    web:
      exposure:
        include: '*'


