server:
  port: 4003


spring:
  application:
    name: eureka-ribbon-hystrix-consumer


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://peer1:2000/eureka/


management:
  security:
    enabled: false

# /health 访问详细信息
endpoints:
  health:
    sensitive: false